AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Example of processing messages on an SQS queue with Lambda
Resources:
  ListenerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/listener.index
      Runtime: nodejs12.x
      Events:
        Api:
          Type: Api
          Properties:
            Path: /ratings
            Method: get
  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/worker.index
      Runtime: nodejs12.x
      Events:
        Api:
          Type: Api
          Properties:
            Path: /sss
            Method: get
  MySqsQueue:
    Type: AWS::SQS::Queue
